### ISSUE TITLE
File 'TSUN.repl.generated.ts' is not under 'rootDir'

### ISSUE THREAD

**Issue by yinso** [HerringtonDarkholme/typescript-repl#12]
Hi,

I installed tsun via `npm install -g tsun`, and then just want to play with typescript, 

```
$ tsun
TSUN : TypeScript Upgraded Node
type in TypeScript expression to evaluate
type :help for commands in repl
> 1
File 'TSUN.repl.generated.ts' is not under 'rootDir' <current_root/src>. 'rootDir' is expected to contain all source files.
```

How do I resolve this problem? Thanks.

**Comment by HerringtonDarkholme** [comment]
Hi, are you firing up tsun in a directory with tsconfig.json? That may be the problem.

**Comment by yinso** [comment]
Yes. I wanted to adhoc test my project to be sure they work as expected, so `tsconfig.json` is there in my project.

Is there a way to get this issue resolved - i.e. can `tsun` look for the existence of tsconfig and then store its code under the new root dir if it's there? Thanks.

**Comment by HerringtonDarkholme** [comment]
Can you give me a minimal setup for debugging?
I'd like to fix this.

**Comment by yinso** [comment]
`<projectDir>/tsconfig.json`:

```
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "module": "commonjs",
        "target": "ES5",
        "outDir": "lib",
        "rootDir": "src"
    }
}
```

`<projectDir/src/foo.ts>`:

```
export function add(a, b) {
  return a + b
}
```

start `tsun` at `<projectDir>`:

```
$ tsun
TSUN : TypeScript Upgraded Node
type in TypeScript expression to evaluate
type :help for commands in repl

> 1
File 'TSUN.repl.generated.ts' is not under 'rootDir' <projectDir/src>. 'rootDir' is expected to contain all source files.
> import * as F from './src/foo'
File 'TSUN.repl.generated.ts' is not under 'rootDir' <projectDir/src>. 'rootDir' is expected to contain all source files.
```

**Comment by HerringtonDarkholme** [comment]
Thank you for report! Fixed in https://github.com/HerringtonDarkholme/typescript-repl/commit/aeda90a70f514b3cc6cd46539bff70557afc1d68.

I will publish a new release then.

**Comment by HerringtonDarkholme** [comment]
Version Bumped!

**Comment by yinso** [comment]
Awesome thanks!
