### ISSUE TITLE
Unexpected token Error 

### ISSUE THREAD

**Issue by harshattray** [HerringtonDarkholme/typescript-repl#14]
![screen shot 2016-09-08 at 12 34 56 pm](https://cloud.githubusercontent.com/assets/3311805/18340131/da12a874-75c0-11e6-826f-665f3ecbb413.png)

**Comment by HerringtonDarkholme** [comment]
I cannot reproduce this. This is probably due to a bad tsconfig.json. Please give tsun another try in a clean directory.

Please report more background information.

**Comment by harshattray** [comment]
This error occurs when we try to acess tsun in a local project after installing it globally .

solved it by using npm link .. :sweat_smile:
