### ISSUE TITLE
Errors doesn't show up immediately in paste mode.

### ISSUE THREAD

**Issue by RGBD** [HerringtonDarkholme/typescript-repl#20]
Error doesn't show up immediately after evaluating code in paste mode.
Error shows up after __every__ following evaluations.
Steps to reproduce:
```
% tsun
TSUN : TypeScript Upgraded Node
type in TypeScript expression to evaluate
type :help for commands in repl

> const a = 2;
undefined
> :paste
// entering paste mode, press ctrl-d to evaluate

a = 3
evaluating...
3
> 
Cannot assign to 'a' because it is a constant or a read-only property.
> 2 + 3
Cannot assign to 'a' because it is a constant or a read-only property.
> 
```
Expected behaviour: print error immediately after evaluation.

**Comment by HerringtonDarkholme** [comment]
Fixed in https://github.com/HerringtonDarkholme/typescript-repl/commit/a374916817bdb4393c5cc1baba791b000be9b033
