### ISSUE TITLE
install failed with UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by xcstream** [HerringtonDarkholme/typescript-repl#22]
➜  typescript-repl git:(master) ✗ npm i -g typescript
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
/usr/local/lib
└── typescript@2.2.1 

➜  typescript-repl git:(master) ✗ npm i -g tsun               
/usr/local/bin/tsun -> /usr/local/lib/node_modules/tsun/bin/tsun
/usr/local/lib
├── tsun@0.3.7 
└── UNMET PEER DEPENDENCY typescript@>=2.0.0

npm WARN tsun@0.3.7 requires a peer of typescript@>=2.0.0 but none was installed.

**Comment by HerringtonDarkholme** [comment]
Don't worry. It will work fine.
