### ISSUE TITLE
UNMET PEER DEPENDENCY typescript@>=2.0.0, although Typescript 2.3.2 installed

### ISSUE THREAD

**Issue by anatoly314** [HerringtonDarkholme/typescript-repl#25]
Trying to install `tsun` but getting the following error:

```
anatolyt1-mac:~ anatolyt$ sudo npm install -g tsun
/usr/local/bin/tsun -> /usr/local/lib/node_modules/tsun/bin/tsun
/usr/local/lib
├── tsun@0.3.8
└── UNMET PEER DEPENDENCY typescript@>=2.0.0
```

although `Typescript@2.3.2` installed globally. When I invoke `tsun` from command line it works.

**Comment by pengisgood** [comment]
I have the same problem......

**Comment by HerringtonDarkholme** [comment]
I don't know why npm complains about it but `tsun` will work any way.

**Comment by HerringtonDarkholme** [comment]
https://github.com/npm/npm/issues/9857

NPM doesn't want to fix it :/
