### ISSUE TITLE
Install packages

### ISSUE THREAD

**Issue by masaeedu** [HerringtonDarkholme/typescript-repl#26]
I'm not sure if the ability to install packages from npm into the temporary environment is already implemented, couldn't see it in the readme. Would be great if you could do `:install ...` with autocomplete from npm.

**Comment by HerringtonDarkholme** [comment]
Currently tsun is package sensitive. That means, if you fire `tsun` in an npm directory it will automatically load all typings in that directory.

I have no idea how packages can be installed temporarily..
